In [41]:
from Bio.Cluster import kcluster
import numpy as np
sequences = [
    'ATCGTCGGAATCCCA',
    'ATCGTCGGAATTCCA',
    'ATACTCGGAATCCCA',
    'ATCTTCGGAATCCCT'
    ]
matrix = np.asarray([np.frombuffer(bytes(s,'UTF-8'), dtype=np.uint8) for s in sequences])
clusterid, error, nfound = kcluster(matrix)

In [42]:
clusterid, error, nfound

(array([0, 0, 0, 1], dtype=int32), 13.733333333333334, 1)

In [43]:
matrix

array([[65, 84, 67, 71, 84, 67, 71, 71, 65, 65, 84, 67, 67, 67, 65],
       [65, 84, 67, 71, 84, 67, 71, 71, 65, 65, 84, 84, 67, 67, 65],
       [65, 84, 65, 67, 84, 67, 71, 71, 65, 65, 84, 67, 67, 67, 65],
       [65, 84, 67, 84, 84, 67, 71, 71, 65, 65, 84, 67, 67, 67, 84]],
      dtype=uint8)

In [50]:
from Bio.Cluster import kmedoids
from Bio.Cluster import distancematrix
distance = distancematrix(matrix)
clusterid, error, nfound = kmedoids(distance)
print(clusterid)

[0 0 2 0]


In [51]:
distance

[array([], dtype=float64),
 array([19.26666667]),
 array([ 1.33333333, 20.6       ]),
 array([35.33333333, 54.6       , 43.6       ])]

In [53]:
from Bio.Cluster import treecluster
tree = treecluster(matrix)

In [54]:
print(tree)

(2, 0): 1.33333
(1, -1): 20.6
(3, -2): 54.6


In [55]:
from Bio.Cluster import somcluster
clusterid, celldata = somcluster(matrix)
print(clusterid)

[[1 0]
 [1 0]
 [1 0]
 [1 0]]


In [57]:
celldata

array([[[ 0.42984903, -0.98493089, -0.63350623,  1.38175614,
         -1.52459638,  0.1926566 , -0.1336591 ,  0.84398655,
          1.03844029, -0.94466803, -1.56567315,  0.56071869,
          0.2240029 , -1.50129525, -1.18419319]],

       [[ 0.20632002, -1.57913146, -0.05944832, -1.00265061,
          1.63699393,  1.64689379,  0.98034587, -0.19926861,
         -0.34580009,  0.274372  , -1.54454702,  1.22993715,
         -0.45221578,  0.78137922, -0.39224749]]])